name: Trasgo Front Actions
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: init
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'
      - name: Build
        run: |
          npm install
          npm run build
      - name: Publish website
        uses: lbertenasco/s3-deploy@v1.2.4
        with:
          folder: out
          bucket: main-trasgo-cl
          dist-id: EOMVOC7JKWC3H
          invalidation: /*
